// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `event_from_json`, `event_to_json`, `get_mls`, `identity_from_secret_hex`, `persist_address_state`, `reconstruct_keys`, `save_keys_to_db`, `save_pending_keys_to_db`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PendingFriendRequest`, `V2State`, `V2`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`

Future<String> initV2({
  required String nostrPrivkeyHex,
  required String dbPath,
  required String dbKey,
  required int deviceId,
}) => RustLib.instance.api.crateApiV2InitV2(
  nostrPrivkeyHex: nostrPrivkeyHex,
  dbPath: dbPath,
  dbKey: dbKey,
  deviceId: deviceId,
);

/// Destroy an identity and release its resources.
Future<void> destroyIdentity({required String pubkey}) =>
    RustLib.instance.api.crateApiV2DestroyIdentity(pubkey: pubkey);

/// List all initialized identity pubkeys.
Future<List<String>> listIdentities() =>
    RustLib.instance.api.crateApiV2ListIdentities();

Future<V2FriendRequestResult> createFriendRequest({
  required String pubkey,
  required String peerNpub,
  required String displayName,
}) => RustLib.instance.api.crateApiV2CreateFriendRequest(
  pubkey: pubkey,
  peerNpub: peerNpub,
  displayName: displayName,
);

Future<V2IncomingFriendRequest> receiveFriendRequest({
  required String pubkey,
  required String eventJson,
}) => RustLib.instance.api.crateApiV2ReceiveFriendRequest(
  pubkey: pubkey,
  eventJson: eventJson,
);

Future<V2AcceptResult> acceptFriendRequest({
  required String pubkey,
  required String eventJson,
  required String myDisplayName,
}) => RustLib.instance.api.crateApiV2AcceptFriendRequest(
  pubkey: pubkey,
  eventJson: eventJson,
  myDisplayName: myDisplayName,
);

/// Complete a pending friend request by processing the approve event from the peer.
///
/// After `create_friend_request`, the requester's Signal state lives in `pending_frs`.
/// When the peer accepts and sends back a Mode 1 approve event to firstInbox,
/// this function decrypts it, moves the Signal participant to `peers`, and
/// establishes the address manager — completing the PQXDH handshake on this side.
Future<V2CompleteFriendRequestResult> completeFriendRequest({
  required String pubkey,
  required String firstInboxPubkey,
  required String eventJson,
}) => RustLib.instance.api.crateApiV2CompleteFriendRequest(
  pubkey: pubkey,
  firstInboxPubkey: firstInboxPubkey,
  eventJson: eventJson,
);

Future<V2EncryptResult> encrypt({
  required String pubkey,
  required String peerSignalId,
  required String plaintext,
  required int remoteDeviceId,
}) => RustLib.instance.api.crateApiV2Encrypt(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
  plaintext: plaintext,
  remoteDeviceId: remoteDeviceId,
);

Future<V2DecryptResult> decrypt({
  required String pubkey,
  required String peerSignalId,
  required String ciphertextBase64,
  required int remoteDeviceId,
}) => RustLib.instance.api.crateApiV2Decrypt(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
  ciphertextBase64: ciphertextBase64,
  remoteDeviceId: remoteDeviceId,
);

Future<String> wrapEvent({
  required String pubkey,
  required String innerContent,
  required String receiverNpub,
}) => RustLib.instance.api.crateApiV2WrapEvent(
  pubkey: pubkey,
  innerContent: innerContent,
  receiverNpub: receiverNpub,
);

Future<V2UnwrappedEvent> unwrapEvent({
  required String pubkey,
  required String eventJson,
}) => RustLib.instance.api.crateApiV2UnwrapEvent(
  pubkey: pubkey,
  eventJson: eventJson,
);

Future<String> fetchRelayFees({
  required String pubkey,
  required String relayUrl,
}) => RustLib.instance.api.crateApiV2FetchRelayFees(
  pubkey: pubkey,
  relayUrl: relayUrl,
);

Future<String> stampEvent({
  required String eventJson,
  required String cashuToken,
}) => RustLib.instance.api.crateApiV2StampEvent(
  eventJson: eventJson,
  cashuToken: cashuToken,
);

Future<String> deriveReceivingAddress({
  required String privateKeyHex,
  required String publicKeyHex,
}) => RustLib.instance.api.crateApiV2DeriveReceivingAddress(
  privateKeyHex: privateKeyHex,
  publicKeyHex: publicKeyHex,
);

Future<List<String>> getAllReceivingAddresses({
  required String pubkey,
  required String peerSignalId,
}) => RustLib.instance.api.crateApiV2GetAllReceivingAddresses(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
);

Future<String> buildTextMessage({required String text}) =>
    RustLib.instance.api.crateApiV2BuildTextMessage(text: text);

Future<String> buildFriendRequestMessage({required String payloadJson}) =>
    RustLib.instance.api.crateApiV2BuildFriendRequestMessage(
      payloadJson: payloadJson,
    );

Future<V2ParsedMessage> parseMessage({required String json}) =>
    RustLib.instance.api.crateApiV2ParseMessage(json: json);

Future<void> registerPeer({
  required String pubkey,
  required String peerSignalId,
  required String peerNostrPubkey,
  String? firstInbox,
}) => RustLib.instance.api.crateApiV2RegisterPeer(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
  peerNostrPubkey: peerNostrPubkey,
  firstInbox: firstInbox,
);

Future<String> resolveSendAddress({
  required String pubkey,
  required String peerSignalId,
}) => RustLib.instance.api.crateApiV2ResolveSendAddress(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
);

/// List all known peers from DB.
Future<List<String>> listPeers({required String pubkey}) =>
    RustLib.instance.api.crateApiV2ListPeers(pubkey: pubkey);

/// Check if we have a session with a peer.
Future<bool> hasPeerSession({
  required String pubkey,
  required String peerSignalId,
}) => RustLib.instance.api.crateApiV2HasPeerSession(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
);

/// Delete a peer and all associated state.
Future<void> deletePeer({
  required String pubkey,
  required String peerSignalId,
}) => RustLib.instance.api.crateApiV2DeletePeer(
  pubkey: pubkey,
  peerSignalId: peerSignalId,
);

/// Check if an event was already processed (deduplication).
Future<bool> isEventProcessed({
  required String pubkey,
  required String eventId,
}) => RustLib.instance.api.crateApiV2IsEventProcessed(
  pubkey: pubkey,
  eventId: eventId,
);

/// Mark an event as processed.
Future<void> markEventProcessed({
  required String pubkey,
  required String eventId,
}) => RustLib.instance.api.crateApiV2MarkEventProcessed(
  pubkey: pubkey,
  eventId: eventId,
);

/// Get the current device ID.
Future<int> getDeviceId({required String pubkey}) =>
    RustLib.instance.api.crateApiV2GetDeviceId(pubkey: pubkey);

/// Initialize MLS subsystem.
Future<void> mlsInit({required String pubkey}) =>
    RustLib.instance.api.crateApiV2MlsInit(pubkey: pubkey);

/// Generate a KeyPackage (base64-encoded).
Future<String> mlsGenerateKeyPackage({required String pubkey}) =>
    RustLib.instance.api.crateApiV2MlsGenerateKeyPackage(pubkey: pubkey);

/// Create a new MLS group.
Future<void> mlsCreateGroup({
  required String pubkey,
  required String groupId,
  required String name,
}) => RustLib.instance.api.crateApiV2MlsCreateGroup(
  pubkey: pubkey,
  groupId: groupId,
  name: name,
);

/// Add members. key_packages_base64_json: JSON array of base64 KeyPackage bytes.
Future<V2MlsAddMembersResult> mlsAddMembers({
  required String pubkey,
  required String groupId,
  required String keyPackagesBase64Json,
}) => RustLib.instance.api.crateApiV2MlsAddMembers(
  pubkey: pubkey,
  groupId: groupId,
  keyPackagesBase64Json: keyPackagesBase64Json,
);

/// Join a group via Welcome (base64). Returns group_id.
Future<String> mlsJoinGroup({
  required String pubkey,
  required String welcomeBase64,
}) => RustLib.instance.api.crateApiV2MlsJoinGroup(
  pubkey: pubkey,
  welcomeBase64: welcomeBase64,
);

/// Encrypt plaintext for MLS group. Returns ciphertext base64.
Future<String> mlsEncrypt({
  required String pubkey,
  required String groupId,
  required String plaintext,
}) => RustLib.instance.api.crateApiV2MlsEncrypt(
  pubkey: pubkey,
  groupId: groupId,
  plaintext: plaintext,
);

/// Decrypt MLS ciphertext (base64). Returns plaintext + sender_id.
Future<V2MlsDecryptResult> mlsDecrypt({
  required String pubkey,
  required String groupId,
  required String ciphertextBase64,
}) => RustLib.instance.api.crateApiV2MlsDecrypt(
  pubkey: pubkey,
  groupId: groupId,
  ciphertextBase64: ciphertextBase64,
);

/// Remove members by nostr ID (JSON array). Returns commit base64.
Future<String> mlsRemoveMembers({
  required String pubkey,
  required String groupId,
  required String memberIdsJson,
}) => RustLib.instance.api.crateApiV2MlsRemoveMembers(
  pubkey: pubkey,
  groupId: groupId,
  memberIdsJson: memberIdsJson,
);

/// Self-update (key rotation). Returns commit base64.
Future<String> mlsSelfUpdate({
  required String pubkey,
  required String groupId,
}) => RustLib.instance.api.crateApiV2MlsSelfUpdate(
  pubkey: pubkey,
  groupId: groupId,
);

/// Leave a group. Returns proposal base64.
Future<String> mlsLeaveGroup({
  required String pubkey,
  required String groupId,
}) => RustLib.instance.api.crateApiV2MlsLeaveGroup(
  pubkey: pubkey,
  groupId: groupId,
);

/// Process incoming MLS Commit (base64).
Future<void> mlsProcessCommit({
  required String pubkey,
  required String groupId,
  required String commitBase64,
}) => RustLib.instance.api.crateApiV2MlsProcessCommit(
  pubkey: pubkey,
  groupId: groupId,
  commitBase64: commitBase64,
);

/// Derive shared MLS temp inbox address.
Future<String> mlsDeriveTempInbox({
  required String pubkey,
  required String groupId,
}) => RustLib.instance.api.crateApiV2MlsDeriveTempInbox(
  pubkey: pubkey,
  groupId: groupId,
);

/// List group members (nostr IDs).
Future<List<String>> mlsGroupMembers({
  required String pubkey,
  required String groupId,
}) => RustLib.instance.api.crateApiV2MlsGroupMembers(
  pubkey: pubkey,
  groupId: groupId,
);

/// Update group context. Returns commit base64.
Future<String> mlsUpdateGroup({
  required String pubkey,
  required String groupId,
  String? name,
  String? status,
  String? adminPubkeysJson,
}) => RustLib.instance.api.crateApiV2MlsUpdateGroup(
  pubkey: pubkey,
  groupId: groupId,
  name: name,
  status: status,
  adminPubkeysJson: adminPubkeysJson,
);

/// Get group info.
Future<V2MlsGroupInfo> mlsGroupInfo({
  required String pubkey,
  required String groupId,
}) => RustLib.instance.api.crateApiV2MlsGroupInfo(
  pubkey: pubkey,
  groupId: groupId,
);

/// Connect to Nostr relays.
/// `relay_urls_json`: JSON array of relay URLs, e.g. `["wss://relay.damus.io","wss://relay.keychat.io"]`
Future<void> relayConnect({
  required String pubkey,
  required String relayUrlsJson,
}) => RustLib.instance.api.crateApiV2RelayConnect(
  pubkey: pubkey,
  relayUrlsJson: relayUrlsJson,
);

/// Subscribe to kind:1059 events for the given pubkeys.
/// `pubkeys_json`: JSON array of hex pubkeys to listen on.
/// `since_timestamp`: Unix timestamp (0 = no filter).
/// Starts a background listener that buffers incoming events.
Future<void> relaySubscribe({
  required String pubkey,
  required String pubkeysJson,
  required BigInt sinceTimestamp,
}) => RustLib.instance.api.crateApiV2RelaySubscribe(
  pubkey: pubkey,
  pubkeysJson: pubkeysJson,
  sinceTimestamp: sinceTimestamp,
);

/// Fetch the next buffered relay event (non-blocking).
/// Returns event JSON or empty string if no event available.
Future<String> relayNextEvent({required String pubkey}) =>
    RustLib.instance.api.crateApiV2RelayNextEvent(pubkey: pubkey);

/// Fetch the next relay event, blocking up to `timeout_ms` milliseconds.
/// Returns event JSON or empty string on timeout.
Future<String> relayNextEventBlocking({
  required String pubkey,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiV2RelayNextEventBlocking(
  pubkey: pubkey,
  timeoutMs: timeoutMs,
);

/// Publish an event to all connected relays.
/// Returns the event ID hex on success.
Future<String> relayPublish({
  required String pubkey,
  required String eventJson,
}) => RustLib.instance.api.crateApiV2RelayPublish(
  pubkey: pubkey,
  eventJson: eventJson,
);

/// Disconnect from all relays.
Future<void> relayDisconnect({required String pubkey}) =>
    RustLib.instance.api.crateApiV2RelayDisconnect(pubkey: pubkey);

/// Check if relay transport is connected.
Future<bool> relayIsConnected({required String pubkey}) =>
    RustLib.instance.api.crateApiV2RelayIsConnected(pubkey: pubkey);

class V2AcceptResult {
  final String eventJson;
  final String peerSignalIdentity;

  const V2AcceptResult({
    required this.eventJson,
    required this.peerSignalIdentity,
  });

  @override
  int get hashCode => eventJson.hashCode ^ peerSignalIdentity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2AcceptResult &&
          runtimeType == other.runtimeType &&
          eventJson == other.eventJson &&
          peerSignalIdentity == other.peerSignalIdentity;
}

class V2CompleteFriendRequestResult {
  final String peerSignalIdentity;
  final String peerNostrPubkey;
  final String approveMessageJson;
  final List<String> newReceivingAddresses;

  const V2CompleteFriendRequestResult({
    required this.peerSignalIdentity,
    required this.peerNostrPubkey,
    required this.approveMessageJson,
    required this.newReceivingAddresses,
  });

  @override
  int get hashCode =>
      peerSignalIdentity.hashCode ^
      peerNostrPubkey.hashCode ^
      approveMessageJson.hashCode ^
      newReceivingAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2CompleteFriendRequestResult &&
          runtimeType == other.runtimeType &&
          peerSignalIdentity == other.peerSignalIdentity &&
          peerNostrPubkey == other.peerNostrPubkey &&
          approveMessageJson == other.approveMessageJson &&
          newReceivingAddresses == other.newReceivingAddresses;
}

class V2DecryptResult {
  final String plaintext;
  final String senderAddress;
  final List<String> newReceivingAddresses;

  const V2DecryptResult({
    required this.plaintext,
    required this.senderAddress,
    required this.newReceivingAddresses,
  });

  @override
  int get hashCode =>
      plaintext.hashCode ^
      senderAddress.hashCode ^
      newReceivingAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2DecryptResult &&
          runtimeType == other.runtimeType &&
          plaintext == other.plaintext &&
          senderAddress == other.senderAddress &&
          newReceivingAddresses == other.newReceivingAddresses;
}

class V2EncryptResult {
  final String ciphertextBase64;
  final String senderAddress;
  final List<String> newReceivingAddresses;

  const V2EncryptResult({
    required this.ciphertextBase64,
    required this.senderAddress,
    required this.newReceivingAddresses,
  });

  @override
  int get hashCode =>
      ciphertextBase64.hashCode ^
      senderAddress.hashCode ^
      newReceivingAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2EncryptResult &&
          runtimeType == other.runtimeType &&
          ciphertextBase64 == other.ciphertextBase64 &&
          senderAddress == other.senderAddress &&
          newReceivingAddresses == other.newReceivingAddresses;
}

class V2FriendRequestResult {
  final String eventJson;
  final String firstInboxPubkey;
  final String firstInboxSecret;
  final String signalIdentityHex;

  const V2FriendRequestResult({
    required this.eventJson,
    required this.firstInboxPubkey,
    required this.firstInboxSecret,
    required this.signalIdentityHex,
  });

  @override
  int get hashCode =>
      eventJson.hashCode ^
      firstInboxPubkey.hashCode ^
      firstInboxSecret.hashCode ^
      signalIdentityHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2FriendRequestResult &&
          runtimeType == other.runtimeType &&
          eventJson == other.eventJson &&
          firstInboxPubkey == other.firstInboxPubkey &&
          firstInboxSecret == other.firstInboxSecret &&
          signalIdentityHex == other.signalIdentityHex;
}

class V2IncomingFriendRequest {
  final String senderNpub;
  final String senderName;
  final String signalIdentityKey;
  final String firstInbox;
  final String deviceId;
  final int signalSignedPrekeyId;
  final String signalSignedPrekey;
  final String signalSignedPrekeySignature;
  final int signalOneTimePrekeyId;
  final String signalOneTimePrekey;
  final int signalKyberPrekeyId;
  final String signalKyberPrekey;
  final String signalKyberPrekeySignature;
  final String globalSign;
  final String payloadJson;

  const V2IncomingFriendRequest({
    required this.senderNpub,
    required this.senderName,
    required this.signalIdentityKey,
    required this.firstInbox,
    required this.deviceId,
    required this.signalSignedPrekeyId,
    required this.signalSignedPrekey,
    required this.signalSignedPrekeySignature,
    required this.signalOneTimePrekeyId,
    required this.signalOneTimePrekey,
    required this.signalKyberPrekeyId,
    required this.signalKyberPrekey,
    required this.signalKyberPrekeySignature,
    required this.globalSign,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      senderNpub.hashCode ^
      senderName.hashCode ^
      signalIdentityKey.hashCode ^
      firstInbox.hashCode ^
      deviceId.hashCode ^
      signalSignedPrekeyId.hashCode ^
      signalSignedPrekey.hashCode ^
      signalSignedPrekeySignature.hashCode ^
      signalOneTimePrekeyId.hashCode ^
      signalOneTimePrekey.hashCode ^
      signalKyberPrekeyId.hashCode ^
      signalKyberPrekey.hashCode ^
      signalKyberPrekeySignature.hashCode ^
      globalSign.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2IncomingFriendRequest &&
          runtimeType == other.runtimeType &&
          senderNpub == other.senderNpub &&
          senderName == other.senderName &&
          signalIdentityKey == other.signalIdentityKey &&
          firstInbox == other.firstInbox &&
          deviceId == other.deviceId &&
          signalSignedPrekeyId == other.signalSignedPrekeyId &&
          signalSignedPrekey == other.signalSignedPrekey &&
          signalSignedPrekeySignature == other.signalSignedPrekeySignature &&
          signalOneTimePrekeyId == other.signalOneTimePrekeyId &&
          signalOneTimePrekey == other.signalOneTimePrekey &&
          signalKyberPrekeyId == other.signalKyberPrekeyId &&
          signalKyberPrekey == other.signalKyberPrekey &&
          signalKyberPrekeySignature == other.signalKyberPrekeySignature &&
          globalSign == other.globalSign &&
          payloadJson == other.payloadJson;
}

class V2MlsAddMembersResult {
  final String commitBase64;
  final String welcomeBase64;

  const V2MlsAddMembersResult({
    required this.commitBase64,
    required this.welcomeBase64,
  });

  @override
  int get hashCode => commitBase64.hashCode ^ welcomeBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2MlsAddMembersResult &&
          runtimeType == other.runtimeType &&
          commitBase64 == other.commitBase64 &&
          welcomeBase64 == other.welcomeBase64;
}

class V2MlsDecryptResult {
  final String plaintext;
  final String senderId;

  const V2MlsDecryptResult({required this.plaintext, required this.senderId});

  @override
  int get hashCode => plaintext.hashCode ^ senderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2MlsDecryptResult &&
          runtimeType == other.runtimeType &&
          plaintext == other.plaintext &&
          senderId == other.senderId;
}

class V2MlsGroupInfo {
  final String name;
  final String status;
  final String adminsJson;

  const V2MlsGroupInfo({
    required this.name,
    required this.status,
    required this.adminsJson,
  });

  @override
  int get hashCode => name.hashCode ^ status.hashCode ^ adminsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2MlsGroupInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          adminsJson == other.adminsJson;
}

class V2ParsedMessage {
  final String kind;
  final String contentJson;

  const V2ParsedMessage({required this.kind, required this.contentJson});

  @override
  int get hashCode => kind.hashCode ^ contentJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2ParsedMessage &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          contentJson == other.contentJson;
}

class V2UnwrappedEvent {
  final String senderNpub;
  final String content;
  final BigInt timestamp;

  const V2UnwrappedEvent({
    required this.senderNpub,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      senderNpub.hashCode ^ content.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is V2UnwrappedEvent &&
          runtimeType == other.runtimeType &&
          senderNpub == other.senderNpub &&
          content == other.content &&
          timestamp == other.timestamp;
}
