// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api_v2.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1779808993;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'keychat_rust_ffi_plugin_v2',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiV2InitV2({required String nostrPrivkeyHex});

  Future<V2AcceptResult> crateApiV2V2AcceptFriendRequest(
      {required String eventJson, required String myDisplayName});

  Future<String> crateApiV2V2BuildFriendRequestMessage(
      {required String payloadJson});

  Future<String> crateApiV2V2BuildTextMessage({required String text});

  Future<V2FriendRequestResult> crateApiV2V2CreateFriendRequest(
      {required String peerNpub, required String displayName});

  Future<V2DecryptResult> crateApiV2V2Decrypt(
      {required String peerSignalId, required String ciphertextBase64});

  Future<String> crateApiV2V2DeriveReceivingAddress(
      {required String privateKeyHex, required String publicKeyHex});

  Future<V2EncryptResult> crateApiV2V2Encrypt(
      {required String peerSignalId, required String plaintext});

  Future<String> crateApiV2V2FetchRelayFees({required String relayUrl});

  Future<List<String>> crateApiV2V2GetAllReceivingAddresses(
      {required String peerSignalId});

  Future<V2ParsedMessage> crateApiV2V2ParseMessage({required String json});

  Future<V2IncomingFriendRequest> crateApiV2V2ReceiveFriendRequest(
      {required String eventJson});

  Future<void> crateApiV2V2RegisterPeer(
      {required String peerSignalId,
      required String peerNostrPubkey,
      String? firstInbox});

  Future<String> crateApiV2V2ResolveSendAddress({required String peerSignalId});

  Future<String> crateApiV2V2StampEvent(
      {required String eventJson, required String cashuToken});

  Future<V2UnwrappedEvent> crateApiV2V2UnwrapEvent({required String eventJson});

  Future<String> crateApiV2V2WrapEvent(
      {required String innerContent, required String receiverNpub});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiV2InitV2({required String nostrPrivkeyHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nostrPrivkeyHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2InitV2ConstMeta,
      argValues: [nostrPrivkeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2InitV2ConstMeta => const TaskConstMeta(
        debugName: "init_v2",
        argNames: ["nostrPrivkeyHex"],
      );

  @override
  Future<V2AcceptResult> crateApiV2V2AcceptFriendRequest(
      {required String eventJson, required String myDisplayName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventJson, serializer);
        sse_encode_String(myDisplayName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_accept_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2AcceptFriendRequestConstMeta,
      argValues: [eventJson, myDisplayName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2AcceptFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "v2_accept_friend_request",
        argNames: ["eventJson", "myDisplayName"],
      );

  @override
  Future<String> crateApiV2V2BuildFriendRequestMessage(
      {required String payloadJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(payloadJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2BuildFriendRequestMessageConstMeta,
      argValues: [payloadJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2BuildFriendRequestMessageConstMeta =>
      const TaskConstMeta(
        debugName: "v2_build_friend_request_message",
        argNames: ["payloadJson"],
      );

  @override
  Future<String> crateApiV2V2BuildTextMessage({required String text}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2BuildTextMessageConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2BuildTextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "v2_build_text_message",
        argNames: ["text"],
      );

  @override
  Future<V2FriendRequestResult> crateApiV2V2CreateFriendRequest(
      {required String peerNpub, required String displayName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerNpub, serializer);
        sse_encode_String(displayName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_friend_request_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2CreateFriendRequestConstMeta,
      argValues: [peerNpub, displayName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2CreateFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "v2_create_friend_request",
        argNames: ["peerNpub", "displayName"],
      );

  @override
  Future<V2DecryptResult> crateApiV2V2Decrypt(
      {required String peerSignalId, required String ciphertextBase64}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerSignalId, serializer);
        sse_encode_String(ciphertextBase64, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_decrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2DecryptConstMeta,
      argValues: [peerSignalId, ciphertextBase64],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2DecryptConstMeta => const TaskConstMeta(
        debugName: "v2_decrypt",
        argNames: ["peerSignalId", "ciphertextBase64"],
      );

  @override
  Future<String> crateApiV2V2DeriveReceivingAddress(
      {required String privateKeyHex, required String publicKeyHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(publicKeyHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2DeriveReceivingAddressConstMeta,
      argValues: [privateKeyHex, publicKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2DeriveReceivingAddressConstMeta =>
      const TaskConstMeta(
        debugName: "v2_derive_receiving_address",
        argNames: ["privateKeyHex", "publicKeyHex"],
      );

  @override
  Future<V2EncryptResult> crateApiV2V2Encrypt(
      {required String peerSignalId, required String plaintext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerSignalId, serializer);
        sse_encode_String(plaintext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_encrypt_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2EncryptConstMeta,
      argValues: [peerSignalId, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2EncryptConstMeta => const TaskConstMeta(
        debugName: "v2_encrypt",
        argNames: ["peerSignalId", "plaintext"],
      );

  @override
  Future<String> crateApiV2V2FetchRelayFees({required String relayUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(relayUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2FetchRelayFeesConstMeta,
      argValues: [relayUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2FetchRelayFeesConstMeta => const TaskConstMeta(
        debugName: "v2_fetch_relay_fees",
        argNames: ["relayUrl"],
      );

  @override
  Future<List<String>> crateApiV2V2GetAllReceivingAddresses(
      {required String peerSignalId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerSignalId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2GetAllReceivingAddressesConstMeta,
      argValues: [peerSignalId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2GetAllReceivingAddressesConstMeta =>
      const TaskConstMeta(
        debugName: "v2_get_all_receiving_addresses",
        argNames: ["peerSignalId"],
      );

  @override
  Future<V2ParsedMessage> crateApiV2V2ParseMessage({required String json}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(json, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_parsed_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2ParseMessageConstMeta,
      argValues: [json],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2ParseMessageConstMeta => const TaskConstMeta(
        debugName: "v2_parse_message",
        argNames: ["json"],
      );

  @override
  Future<V2IncomingFriendRequest> crateApiV2V2ReceiveFriendRequest(
      {required String eventJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_incoming_friend_request,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2ReceiveFriendRequestConstMeta,
      argValues: [eventJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2ReceiveFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "v2_receive_friend_request",
        argNames: ["eventJson"],
      );

  @override
  Future<void> crateApiV2V2RegisterPeer(
      {required String peerSignalId,
      required String peerNostrPubkey,
      String? firstInbox}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerSignalId, serializer);
        sse_encode_String(peerNostrPubkey, serializer);
        sse_encode_opt_String(firstInbox, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2RegisterPeerConstMeta,
      argValues: [peerSignalId, peerNostrPubkey, firstInbox],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2RegisterPeerConstMeta => const TaskConstMeta(
        debugName: "v2_register_peer",
        argNames: ["peerSignalId", "peerNostrPubkey", "firstInbox"],
      );

  @override
  Future<String> crateApiV2V2ResolveSendAddress(
      {required String peerSignalId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(peerSignalId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2ResolveSendAddressConstMeta,
      argValues: [peerSignalId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2ResolveSendAddressConstMeta =>
      const TaskConstMeta(
        debugName: "v2_resolve_send_address",
        argNames: ["peerSignalId"],
      );

  @override
  Future<String> crateApiV2V2StampEvent(
      {required String eventJson, required String cashuToken}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventJson, serializer);
        sse_encode_String(cashuToken, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2StampEventConstMeta,
      argValues: [eventJson, cashuToken],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2StampEventConstMeta => const TaskConstMeta(
        debugName: "v2_stamp_event",
        argNames: ["eventJson", "cashuToken"],
      );

  @override
  Future<V2UnwrappedEvent> crateApiV2V2UnwrapEvent(
      {required String eventJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_v_2_unwrapped_event,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2UnwrapEventConstMeta,
      argValues: [eventJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2UnwrapEventConstMeta => const TaskConstMeta(
        debugName: "v2_unwrap_event",
        argNames: ["eventJson"],
      );

  @override
  Future<String> crateApiV2V2WrapEvent(
      {required String innerContent, required String receiverNpub}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(innerContent, serializer);
        sse_encode_String(receiverNpub, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiV2V2WrapEventConstMeta,
      argValues: [innerContent, receiverNpub],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiV2V2WrapEventConstMeta => const TaskConstMeta(
        debugName: "v2_wrap_event",
        argNames: ["innerContent", "receiverNpub"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  V2AcceptResult dco_decode_v_2_accept_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return V2AcceptResult(
      eventJson: dco_decode_String(arr[0]),
      peerSignalIdentity: dco_decode_String(arr[1]),
    );
  }

  @protected
  V2DecryptResult dco_decode_v_2_decrypt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return V2DecryptResult(
      plaintext: dco_decode_String(arr[0]),
      senderAddress: dco_decode_String(arr[1]),
      newReceivingAddresses: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  V2EncryptResult dco_decode_v_2_encrypt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return V2EncryptResult(
      ciphertextBase64: dco_decode_String(arr[0]),
      senderAddress: dco_decode_String(arr[1]),
      newReceivingAddresses: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  V2FriendRequestResult dco_decode_v_2_friend_request_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return V2FriendRequestResult(
      eventJson: dco_decode_String(arr[0]),
      firstInboxPubkey: dco_decode_String(arr[1]),
      firstInboxSecret: dco_decode_String(arr[2]),
      signalIdentityHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  V2IncomingFriendRequest dco_decode_v_2_incoming_friend_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return V2IncomingFriendRequest(
      senderNpub: dco_decode_String(arr[0]),
      senderName: dco_decode_String(arr[1]),
      signalIdentityKey: dco_decode_String(arr[2]),
      firstInbox: dco_decode_String(arr[3]),
      deviceId: dco_decode_String(arr[4]),
      signalSignedPrekeyId: dco_decode_u_32(arr[5]),
      signalSignedPrekey: dco_decode_String(arr[6]),
      signalSignedPrekeySignature: dco_decode_String(arr[7]),
      signalOneTimePrekeyId: dco_decode_u_32(arr[8]),
      signalOneTimePrekey: dco_decode_String(arr[9]),
      signalKyberPrekeyId: dco_decode_u_32(arr[10]),
      signalKyberPrekey: dco_decode_String(arr[11]),
      signalKyberPrekeySignature: dco_decode_String(arr[12]),
      globalSign: dco_decode_String(arr[13]),
      payloadJson: dco_decode_String(arr[14]),
    );
  }

  @protected
  V2ParsedMessage dco_decode_v_2_parsed_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return V2ParsedMessage(
      kind: dco_decode_String(arr[0]),
      contentJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  V2UnwrappedEvent dco_decode_v_2_unwrapped_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return V2UnwrappedEvent(
      senderNpub: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
      timestamp: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  V2AcceptResult sse_decode_v_2_accept_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventJson = sse_decode_String(deserializer);
    var var_peerSignalIdentity = sse_decode_String(deserializer);
    return V2AcceptResult(
        eventJson: var_eventJson, peerSignalIdentity: var_peerSignalIdentity);
  }

  @protected
  V2DecryptResult sse_decode_v_2_decrypt_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_plaintext = sse_decode_String(deserializer);
    var var_senderAddress = sse_decode_String(deserializer);
    var var_newReceivingAddresses = sse_decode_list_String(deserializer);
    return V2DecryptResult(
        plaintext: var_plaintext,
        senderAddress: var_senderAddress,
        newReceivingAddresses: var_newReceivingAddresses);
  }

  @protected
  V2EncryptResult sse_decode_v_2_encrypt_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphertextBase64 = sse_decode_String(deserializer);
    var var_senderAddress = sse_decode_String(deserializer);
    var var_newReceivingAddresses = sse_decode_list_String(deserializer);
    return V2EncryptResult(
        ciphertextBase64: var_ciphertextBase64,
        senderAddress: var_senderAddress,
        newReceivingAddresses: var_newReceivingAddresses);
  }

  @protected
  V2FriendRequestResult sse_decode_v_2_friend_request_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventJson = sse_decode_String(deserializer);
    var var_firstInboxPubkey = sse_decode_String(deserializer);
    var var_firstInboxSecret = sse_decode_String(deserializer);
    var var_signalIdentityHex = sse_decode_String(deserializer);
    return V2FriendRequestResult(
        eventJson: var_eventJson,
        firstInboxPubkey: var_firstInboxPubkey,
        firstInboxSecret: var_firstInboxSecret,
        signalIdentityHex: var_signalIdentityHex);
  }

  @protected
  V2IncomingFriendRequest sse_decode_v_2_incoming_friend_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_senderNpub = sse_decode_String(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_signalIdentityKey = sse_decode_String(deserializer);
    var var_firstInbox = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_signalSignedPrekeyId = sse_decode_u_32(deserializer);
    var var_signalSignedPrekey = sse_decode_String(deserializer);
    var var_signalSignedPrekeySignature = sse_decode_String(deserializer);
    var var_signalOneTimePrekeyId = sse_decode_u_32(deserializer);
    var var_signalOneTimePrekey = sse_decode_String(deserializer);
    var var_signalKyberPrekeyId = sse_decode_u_32(deserializer);
    var var_signalKyberPrekey = sse_decode_String(deserializer);
    var var_signalKyberPrekeySignature = sse_decode_String(deserializer);
    var var_globalSign = sse_decode_String(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    return V2IncomingFriendRequest(
        senderNpub: var_senderNpub,
        senderName: var_senderName,
        signalIdentityKey: var_signalIdentityKey,
        firstInbox: var_firstInbox,
        deviceId: var_deviceId,
        signalSignedPrekeyId: var_signalSignedPrekeyId,
        signalSignedPrekey: var_signalSignedPrekey,
        signalSignedPrekeySignature: var_signalSignedPrekeySignature,
        signalOneTimePrekeyId: var_signalOneTimePrekeyId,
        signalOneTimePrekey: var_signalOneTimePrekey,
        signalKyberPrekeyId: var_signalKyberPrekeyId,
        signalKyberPrekey: var_signalKyberPrekey,
        signalKyberPrekeySignature: var_signalKyberPrekeySignature,
        globalSign: var_globalSign,
        payloadJson: var_payloadJson);
  }

  @protected
  V2ParsedMessage sse_decode_v_2_parsed_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_contentJson = sse_decode_String(deserializer);
    return V2ParsedMessage(kind: var_kind, contentJson: var_contentJson);
  }

  @protected
  V2UnwrappedEvent sse_decode_v_2_unwrapped_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_senderNpub = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    return V2UnwrappedEvent(
        senderNpub: var_senderNpub,
        content: var_content,
        timestamp: var_timestamp);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_v_2_accept_result(
      V2AcceptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventJson, serializer);
    sse_encode_String(self.peerSignalIdentity, serializer);
  }

  @protected
  void sse_encode_v_2_decrypt_result(
      V2DecryptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.plaintext, serializer);
    sse_encode_String(self.senderAddress, serializer);
    sse_encode_list_String(self.newReceivingAddresses, serializer);
  }

  @protected
  void sse_encode_v_2_encrypt_result(
      V2EncryptResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ciphertextBase64, serializer);
    sse_encode_String(self.senderAddress, serializer);
    sse_encode_list_String(self.newReceivingAddresses, serializer);
  }

  @protected
  void sse_encode_v_2_friend_request_result(
      V2FriendRequestResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventJson, serializer);
    sse_encode_String(self.firstInboxPubkey, serializer);
    sse_encode_String(self.firstInboxSecret, serializer);
    sse_encode_String(self.signalIdentityHex, serializer);
  }

  @protected
  void sse_encode_v_2_incoming_friend_request(
      V2IncomingFriendRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.senderNpub, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.signalIdentityKey, serializer);
    sse_encode_String(self.firstInbox, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_u_32(self.signalSignedPrekeyId, serializer);
    sse_encode_String(self.signalSignedPrekey, serializer);
    sse_encode_String(self.signalSignedPrekeySignature, serializer);
    sse_encode_u_32(self.signalOneTimePrekeyId, serializer);
    sse_encode_String(self.signalOneTimePrekey, serializer);
    sse_encode_u_32(self.signalKyberPrekeyId, serializer);
    sse_encode_String(self.signalKyberPrekey, serializer);
    sse_encode_String(self.signalKyberPrekeySignature, serializer);
    sse_encode_String(self.globalSign, serializer);
    sse_encode_String(self.payloadJson, serializer);
  }

  @protected
  void sse_encode_v_2_parsed_message(
      V2ParsedMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.contentJson, serializer);
  }

  @protected
  void sse_encode_v_2_unwrapped_event(
      V2UnwrappedEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.senderNpub, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_u_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
